#%RAML 1.0 Trait
uses:
  Types: types.raml

responses:
  444:
    description: Internal error occured
    body:
      application/json:
        properties:
          status: Types.Status
          message:
            required: false
            type: string

        example: |
          {
            "status": "internal_error",
            "message": "PlayerException: ..."
          }
  400:
    description: Bad request (malformed data or missing fields)
    body:
      application/json:
        properties:
          status: Types.Status
          message:
            required: false
            type: string
        example: |
          {
            "status": "bad_request",
            "message": "Missing 'sample' field"
          }

  403:
    description: Token is invalid / missing
    body:
      application/json:
        properties:
          status: Types.Status
        example: { "status": "forbidden" }
