#%RAML 1.0 Library
types:
  PlayType:
    type: string
    enum:
      - next
      - queue

  Token:
    type: string
    pattern: .{20}
    maxLength: 20
    minLength: 20
    description: An access token

  Status:
    type: string
    enum:
      - ok
      - forbidden
      - error
      - noop
      - internal_error
      - bad_request

  AudioPosition:
    type: string
    pattern: ([0-9]+:?){1,3}(\.[0-9]+)?
